Description of pgm2bigPgm
pgm2bigPgm
PURPOSE
AUTHOR: Laura Collins (lac32)
SYNOPSIS
function s = pgm2bigPgm(pathname)
DESCRIPTION
 AUTHOR: Laura Collins (lac32)
 LAST MODIFIED: 28/03/16
CROSS-REFERENCE INFORMATION
This function calls:
saveSeries Part of the existing code base from the Congealing Demo
This function is called by:
Enantiomorph ENANTIOMORPH MATLAB code for Enantiomorph.fig
TESTpgmCreation AUTHOR: Laura Collins (lac32)
SOURCE CODE
% AUTHOR: Laura Collins (lac32)
% LAST MODIFIED: 28/03/16
function s = pgm2bigPgm(pathname)
scanDirectory = dir(fullfile(pathname, '*.pgm'));
noOfScans = length(scanDirectory);
filename = strcat(pathname,'/',scanDirectory(1).name);
file=fopen(filename,'r');
if file == -1
  error('Author:Function:OpenFile', 'Cannot open folder: %s', filename);
end
ln1=fgetl(file);
ln2=strsplit(fgetl(file));
if find(strcmp('#', ln2))
    ln2(1) = []; % http://blogs.mathworks.com/videos/2010/03/30/deleting-an-element-from-a-cell-array/
end
squareImageSize = str2double(ln2);
sers=zeros(squareImageSize(1),squareImageSize(2),noOfScans);
for i = 1:noOfScans
    scan = fopen(strcat(pathname,'/',scanDirectory(i).name));
    im=(fread(scan,[squareImageSize(1),squareImageSize(2)],'uchar'));
    sers(:,:,i) = im;
end
outfname=sprintf('%s/big_scan.pgm', pathname);
s=sers(:,:,:);
saveSeries(outfname,permute(s,[2,1,3])); %http://uk.mathworks.com/help/matlab/ref/permute.html - swap rows and columns around for fwrite