Description of deLucaFuzzy
deLucaFuzzy
PURPOSE
Function implementing De Luca & Termini's Fuzzy Entropy algorithm
SYNOPSIS
function entropy = deLucaFuzzy(meanImg)
DESCRIPTION
 Function implementing De Luca & Termini's Fuzzy Entropy algorithm
CROSS-REFERENCE INFORMATION
This function calls:
membership Calculate the membershipDegree of a pixel
This function is called by:
TESTnonProb Test the Membership function
binaryCongeal This function takes a series of images and returns
incrTrans incrTrans
SOURCE CODE
function entropy = deLucaFuzzy(meanImg)
% Function implementing De Luca & Termini's Fuzzy Entropy algorithm
addpath /Users/lauracollins/Git/Major-Project/Source/Development/MEMBERSHIP
[imgMu, lowMu, medMu, highMu] = membership(meanImg);
%imageEnt = cell(size(imgMu,1),size(imgMu,2));
    pixelEnt = -(imgMu(1:numel(imgMu)).*log10(imgMu(1:numel(imgMu)))+(1-imgMu(1:numel(imgMu))).*log10(1-imgMu(1:numel(imgMu))));
    pixelEnt(isnan(pixelEnt))= 0;
    imageEnt = num2cell(pixelEnt);
ent = 1/numel(imgMu)*sum(cellfun(@sum, imageEnt));
entropy=sum(ent);
end