Description of getXfrms
Home > Development > CONGEAL_SUPPORT > getXfrms.m
getXfrms
PURPOSE
SYNOPSIS
function xfrms=getXfrms(transVecs)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
getXfrm
This function is called by:
computeXfrmDistFieldsClip
computeXfrmImgs
computeXfrmImgsClip
SOURCE CODE
function xfrms=getXfrms(transVecs)
[cnt,len]=size(transVecs);
xfrms=zeros(3,3,cnt);
for i=1:cnt
  xfrms(:,:,i)=getXfrm(transVecs(i,:));
end